Changes to GUI + translation keys
Azzy380/Attributes pull request #8
Opened 2023-01-18 13:33 UTC by NerdyPuzzle

Changed the GUI to look more like MCreator's elements + renamed some translation keys for better clarity.

![image](https://user-images.githubusercontent.com/112079900/213184818-ca897194-9a16-4a87-a46d-1c55ffb38f10.png)

2023-01-18 20:12 UTC, Azzy380 commented
Thank you for fixing my terrible English and Gui! 
But can you change `boarder` in lang? (It hurts even my eyes) :>

2023-01-18 20:18 UTC, Azzy380 requested changes
Thank you for fixing my GUI and English!
But can you change `boarder` to `border` in lang?

2023-01-18 20:23 UTC, Azzy380 commented on src/main/resources/lang/texts.properties
> +elementgui.attribute.boarder=Attribute Properties
`boarder` hurts my already bad English :<

2023-01-18 21:25 UTC, NerdyPuzzle commented on src/main/resources/lang/texts.properties
> +elementgui.attribute.boarder=Attribute Properties
Oops!

2023-01-19 10:06 UTC, Azzy380 approved these changes
nice :3

2023-01-19 10:06 UTC, merged